### ISSUE TITLE
JodaTime Support

### ISSUE THREAD

**Issue by otoniel-isidoro-sofist** [joel-costigliola/assertj-db#17]
Why doesn't have support for joda-time yet as others assertJ modules does?

**Comment by regis1512** [comment]
Just to limit the dependencies

**Comment by otoniel-isidoro-sofist** [comment]
You keep it clean and simple I see....but an integration with jodatime could be very useful. What you think?

**Comment by regis1512** [comment]
I hesitate. But in my opinion, i prefer migrate in Java 8 in few months (peharps with a branch in first time like for assertj-core)

**Comment by otoniel-isidoro-sofist** [comment]
Ok Then I will close this issue.
