### ISSUE TITLE
isCloseTo Assertions for Date values with a time tolerance

### ISSUE THREAD

**Issue by otoniel-isidoro** [joel-costigliola/assertj-db#18]
For test purposes on Date assertions should be more easy to use an isCloseTo method with a tolerance instead of use isAfter and isBefore.

Example:
```
assertThat(appInstallTagTable).column("inserted_at").value(0).isCloseTo(TimeUnit.MILISECONDS, 10000, new Date());
assertThat(appInstallTagTable).column("inserted_at").hasValuesCloseTo(TimeUnit.MILISECONDS, 10000, new Date(), new Date(), new Date()); //verify 3 rows values
```

**Comment by regis1512** [comment]
I think it is a good idea.
May be the method could work with Number

**Comment by otoniel-isidoro-sofist** [comment]
You mean use Number for the tolerance parameter?

**Comment by regis1512** [comment]
Yes a number for the tolerance. But i was not clear. Peharps with a example
```
assertThat(appInstallTagTable).column("age").value(0).isCloseTo(tolerance, aValue);
assertThat(appInstallTagTable).column("inserted_at").hasValuesCloseTo(tolerance, value1, value2, value3); //verify 3 rows values
```

**Comment by otoniel-isidoro-sofist** [comment]
Then it assumes that the tolerance is in MILISECONDS?

**Comment by regis1512** [comment]
I did a mistake on the second line.
May be with correction it is better.
For me there is on a side the assertions you suggest for date, time and date/time (for example to compare a date with a date with tolerance).
And on another side the assertions i suggest (with the same name) for number (to compare a number with a number with tolerance).
```
assertThat(appInstallTagTable).column("age").value(0).isNumber().isCloseTo(tolerance, aNumberValue);
assertThat(appInstallTagTable).column("age").isNumber(false).hasValuesCloseTo(tolerance, numberValue1, numberValue2, numberValue3); //verify 3 rows values
```
For me the two possibilities have a meaning

**Comment by regis1512** [comment]
Sorry, when i read my first messages i was really not clear (i did not take enough time to make a good answer)
