### ISSUE TITLE
TEXT column type is not supported (CLOB)

### ISSUE THREAD

**Issue by otoniel-isidoro-sofist** [joel-costigliola/assertj-db#19]
I got a problem. The column type TEXT (not varchar) on h2database is not supported by assertjdb too (It is mapped as object JdbcClob.class that implements the java.sql.CLOB).

Then I see that on AbstractDbData class is not mapped the CLOB type on the collectRowsFromResultSet method.
I suggest just add this type to get it as string as you can see below:
```
switch (type) {
        case Types.DATE:
          objectsList.add(resultSet.getDate(columnName));
          break;
        case Types.TIME:
          objectsList.add(resultSet.getTime(columnName));
          break;
        case Types.TIMESTAMP:
          objectsList.add(resultSet.getTimestamp(columnName));
          break;
        case Types.CLOB:
          objectsList.add(resultSet.getString(columnName));
          break;
        default:
          objectsList.add(resultSet.getObject(columnName));
          break;
        }
```
What do you think?

**Comment by regis1512** [comment]
It is a good idea too.
I think there are other H2 SQL types with problems : BLOB and ARRAY

**Comment by otoniel-isidoro-sofist** [comment]
Ok I already made this and just need to create some tests too. I will create a pull request on another branch.
For the BLOB type I don't know if is better to get it as String or maybe bytes...

**Comment by otoniel-isidoro-sofist** [comment]
I think ARRAY type cannot be mapped as String too:
ARRAY http://h2database.com/html/datatypes.html#array_type
An array of values. Mapped to java.lang.Object[] (arrays of any non-primitive type are also supported).

**Comment by otoniel-isidoro-sofist** [comment]
I still think that can be very useful an assertion point to verify these unmapped types on assertjdb. Otherwise you'll need to implement every type support and it can be unnecessary. The only thing important on this cases is that the input type must be the same value of the expected type.

**Comment by regis1512** [comment]
Yes i have an idea for unmapped types : http://joel-costigliola.github.io/assertj/assertj-core-conditions.html
Please let me time and i will talk with you about an idea.

If you are ok, you can finish your first pull request, after it is fine if you want to implements BLOB and CBLOB like for UUID. 
For CBLOB (http://www.h2database.com/html/datatypes.html#clob_type), i think is possible to map with String
For BLOB (http://www.h2database.com/html/datatypes.html#blob_type), a byte[]
For ARRAY (http://www.h2database.com/html/datatypes.html#array_type), a Object[] so i think we need to take time to think about the way to do

**Comment by otoniel-isidoro-sofist** [comment]
https://github.com/joel-costigliola/assertj-db/pull/20

**Comment by regis1512** [comment]
I add specific tests. Please let me monday evening and you can use that to help you for implementation of specific sql types.

**Comment by regis1512** [comment]
I improve the test class "H2Database_Test". 
I am sorry : it is finally different than a part of your pull request #20 (for the tests)
But i think it better like that because there are all the sql types of H2 and after we can add test on other specific database.

If you want and have time to fork from this point to implement and finish the test it is fine otherwise i can that tomorrow but now it is time to close the eyes ;-)

**Comment by otoniel-isidoro-sofist** [comment]
I closed my pull request about this issue because your implementation is already cover this.
