### ISSUE TITLE
Add insert, update and delete statement execution

### ISSUE THREAD

**Issue by baztian** [joel-costigliola/assertj-db#2]
Would be nice to be able to execute code like this:

    Change change = new Change(source, "DELETE FROM TABLE WHERE ID=?", 1); // Change is similar to Request
    assertThat(change).rowsAffected(1);

**Comment by regis1512** [comment]
For me this issue is done because of the implementation of the concept of Changes with all the linked navigation and assertions.
So i close this issue.
Thanks.
