### ISSUE TITLE
isEqualTo(null) should be possible

### ISSUE THREAD

**Issue by otoniel-isidoro-sofist** [joel-costigliola/assertj-db#21]
In some cases we need to verify if the value on the table is the same value of the expected and the expected value can be null. Then isEqualTo(null) should work if the actual and the expected is null too.
example:
```
Application application = new Application();
application.setName = null;
dao.save(application);
Table applicationTable = new Table(dataSource, DatabaseHelper.APPLICATION_TABLE_NAME);
assertThat(applicationTable).row(0).column("name").value().isEqualTo(application.getName());
```
In this case I dont want to use isNull because I can modify the name attribute from null to a valid value later and my tests still passing.

**Comment by otoniel-isidoro-sofist** [comment]
I can create a generic method assertion for each table too and use it on various tests with valid or null values on each field.
example:
```
 public void assertApplicationTable(List<Application> expectedApplications){
    for(Application application : expectedApplications){
        assertThat(applicationTable)
                .row(expectedApplications.indexOf(application))
                .column("id").value().isEqualTo(application.getId())
                .column("name").value().isEqualTo(application.getName())
                .column("description").value().isEqualTo(application.getDescription())
                .column("application_key").value().isEqualTo(application.getApplicationKey())
                .column("platform").value().isEqualTo(application.getPlatform().getId())
                .column("product_id").value().isEqualTo(application.getProductId())
                .column("package_name").value().isEqualTo(application.getPackageName())
                .column("environment").value().isEqualTo(application.getEnvironment().getId())
                .column("company_id").value().isEqualTo(application.getCompanyId())
                .column("created_at").value().isEqualTo(new DateTimeValue(Timestamp.from(application.getCreatedAt().toInstant())));
    }
}
```

**Comment by otoniel-isidoro-sofist** [comment]
The equality of null=null is not satisfied because of NOT_IDENTIFIED type and on the isEqualTo methods there is a verification on valueType without the type NOT_IDENTIFIED.
example:
```
public static <A extends AbstractAssert> A isEqualTo(A assertion, WritableAssertionInfo info, Object value,
                                                       DateTimeValue expected) {
    AssertionsOnValueType.isOfAnyTypeIn(assertion, info, value, ValueType.DATE, ValueType.DATE_TIME);
[...]
}
```

**Comment by regis1512** [comment]
Understood. It is not an urgent bug but it is more than an enhancement

**Comment by otoniel-isidoro-sofist** [comment]
Just to discuss: I think that the behavior of isAfterOrEqualTo and isBeforeOrEqualTo (I didn't remember if there was more methods like these) are wrong too because it shoud be able to verify if null=null too.

**Comment by regis1512** [comment]
I started to work on this.
I do isEqualTo and isNotEqualTo
For other methods, i do not the real interest for the moment so i think to let like that

**Comment by regis1512** [comment]
Note that it will never be possible to use directly isEqualTo(null) because there is conflict : Java don't know which method is called. But it is possible to implement isEqualTo(Object) and after call it with isEqualTo((Object) null)

**Comment by regis1512** [comment]
Please, give me your test results but for me it is closed

**Comment by otoniel-isidoro-sofist** [comment]
It's ok thx!
