### ISSUE TITLE
[Improvement] Generic Column Type Assertions

### ISSUE THREAD

**Issue by otoniel-isidoro-sofist** [joel-costigliola/assertj-db#22]
Should be possible to make assertions on columns that have type which is not mapped on assertj-db.

**Comment by otoniel-isidoro-sofist** [comment]
Just to don't forget as @regis1512  mentioned on #19  "Yes I have an idea for unmapped types : http://joel-costigliola.github.io/assertj/assertj-core-conditions.html Please let me time and i will talk with you about an idea."

**Comment by regis1512** [comment]
I did not implement my first thought (Condition) but i have started to implement isEqualTo(Object) and isNotEqualTo(Object). These methods work with Object which have an implementation of equals(...) method.
I still need to implement these new methods for the columns of request, table and change.
