### ISSUE TITLE
Double type not mapped to Number

### ISSUE THREAD

**Issue by otoniel-isidoro-sofist** [joel-costigliola/assertj-db#23]
A column was declared as DOUBLE on h2 database and the H2 map it to java.lang.Double but on the ValueType.getType method the java.lang.Double is not mapped to NUMBER.
Then the following assert is not possible because it always get an error:
```    
assertThat(table).hasNumberOfRows(1).column("valor").value(0).isEqualTo(120d);
```
```
java.lang.AssertionError: [Value at index 0 of Column at index 2 (column name : VALOR) of contas table] 
Expecting:
  <120.0>
to be of type
  <NUMBER>
but was of type
  <NOT_IDENTIFIED>
```

**Comment by otoniel-isidoro-sofist** [comment]
Tests for type double are missing too.

**Comment by regis1512** [comment]
Please, give me your test results but for me it is closed

**Comment by otoniel-isidoro-sofist** [comment]
I apologize for the delay in answering but I am very busy these days. I already got this implementation and seems it's ok. Thanks.

**Comment by regis1512** [comment]
No problem. You are welcome. It is the same for all of us. We do that when we have time : there are other priorities in the life and it is very well like that.
