### ISSUE TITLE
Verify columns without row order

### ISSUE THREAD

**Issue by otoniel-isidoro-sofist** [joel-costigliola/assertj-db#25]
Sometimes is necessary to verify columns on a table without an specific row order. It is like contains of assertJ method assertion for Lists. A suggestion would be: 
```
assertThat(table).column("sku").containsValues("teste2", "teste1", "teste3")
```

**Comment by regis1512** [comment]
I will work on that

**Comment by otoniel-isidoro-sofist** [comment]
Good job! Thanks!

**Comment by sisko59** [comment]
It's great function. Thanks!
