### ISSUE TITLE
Cannot edit sql tables having lower case table names in ubantu machine. 

### ISSUE THREAD

**Issue by saniddha** [joel-costigliola/assertj-db#26]
I tried to access a table having a lower case table name and it gave the error message as following. 

axErrorException: Table 'coupon.COUPON_CODE' doesn't exist

but actually i have the command as follows.
Table table = new Table(dataSource,"coupon_code");

I cannot understand why ''coupon_code' becomes uppercase name at the error message and i followed the following tutorial. 
http://www.journaldev.com/2509/jdbc-datasource-example-oracle-mysql-and-apache-dbcp-tutorial

Please can anyone give a solution for this. 

Thanks in advance.

**Comment by otoniel-isidoro-sofist** [comment]
Hi saniddha..by default, table aliases are case sensitive on Unix, but not so on Windows or OS X.
Then you should use the same letter case pattern on every code. Seems like on your code under test is using the Upper Case pattern for table names.

http://dev.mysql.com/doc/refman/5.6/en/identifier-case-sensitivity.html

**Comment by regis1512** [comment]
Hi Saniddha and Otoniel..
If i do not mistake, they are no changes of the case for the name of the table in assertj-db...
But they are some changes for the name of the columns.

@Saniddha : please check your test. If you confirm me a case with anomaly i will control more the code and fix it.

Thanks.

**Comment by saniddha** [comment]
public class TestCouponCreate {

    public static DataSource getMySQLDataSource() {

        MysqlDataSource mysqlDS = null;
        String MYSQL_DB_URL = "jdbc:mysql://db.coupon.mysql/coupon";
        String MYSQL_DB_PASSWORD = "password";
        String MYSQL_DB_USERNAME = "coupon_user";


        mysqlDS = new MysqlDataSource();
        mysqlDS.setURL(MYSQL_DB_URL);
        mysqlDS.setUser(MYSQL_DB_USERNAME);
        mysqlDS.setPassword(MYSQL_DB_PASSWORD);

        return mysqlDS;

    }


    @Test(testName = "Accurate Coupon Request Test")
    @TestCaseId(id = 1)
    public void testCreateCoupon() throws Exception {

        DataSource dataSource;

        RestClient couponClient = ClientBuilder.create("http://core.coupon:8588/coupon-api/v1/coupon/create");
        HttpResponseWrapper httpResponseWrapper = Fire("coupon request").as(() -> couponClient.post()
                .withJsonContent(simpleCouponRequest().build())
                .withTimeout(1000, TimeUnit.MILLISECONDS)
                .send());

        Verify("http response").as(() ->
                httpResponseWrapper
                        .assert200_Ok()
                        .responseContains(statusCode("COUPON-S1000"), statusDescription("Success")));

        Map<String, Object> couponResponse = httpResponseWrapper.getResponseContentMap();
        Map<String, Object> result = (Map<String, Object>) couponResponse.get("result");
        assertThat(result).hasSize(3);
        assertThat((String) result.get("couponCode")).isNotNull().hasSize(6);
        assertThat((String) result.get("requestId")).isNotNull().hasSize(3);

        dataSource = getMySQLDataSource();
        Table table = new Table(dataSource, "coupon_code");

    }
}

This is the code i used. There is a table named "coupon_code" in the database 'coupon' too. But it gives the error message "axErrorException: Table 'coupon.COUPON_CODE' doesn't exist" when do assertions to table data.

**Comment by regis1512** [comment]
Please could you try this code :
```
try (Connection connection = dataSource.getConnection()) {
    try (Statement statement = connection.createStatement()) {
      try (ResultSet resultSet = statement.executeQuery("SELECT * FROM coupon_code")) {
        while (resultSet.next()) {
           ....
        }
      }
    }
}
```

In fact, that is close to be the same code that the code inside loadImpl(Connection connection) method of Table class which load the data. The biggest difference is loadImpl calls getRequest() method. But getRequest() returns the request with no change on the case of the table name.

So for the moment, i think about a parameter in the jdbc driver... But i am not sure at all.

**Comment by saniddha** [comment]
Thnakz for helping. I was my fault. I hadn't given the user the table access right........

**Comment by regis1512** [comment]
You are welcome.
Have a nice day.
