### ISSUE TITLE
Being able to count rows and columns

### ISSUE THREAD

**Issue by agoncal** [joel-costigliola/assertj-db#29]
Today we can assert that a table has a set fix number of rows and columns : 

assertThat(table).hasNumberOfRows(227);
assertThat(table).hasNumberOfRows(12);

But it would be nice to have more flexibility and do things like :

assertThat(table).rows().isGreaterThan(12)
assertThat(table).columns().isLowerThan(10)

**Comment by regis1512** [comment]
Yes. It is a good idea.
I will try to add it soon.
