### ISSUE TITLE
enhance exception message when column does not exist

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-db#34]
When I try to access a column that does not exist I get `org.assertj.db.exception.AssertJDBException: Column <LastNam> does not exist`

I think it would be nice to have a even more helpful error message, which for example displays all available columns (or even similar named columns).

What do you think?

Thank you very much for providing assertj-db by the way.

**Comment by regis1512** [comment]
It is a goor idea.
I will work on it.

**Comment by PascalSchumacher** [comment]
Thanks! :)
