### ISSUE TITLE
assertj-db 1.1.0 does not work with java 7

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-db#37]
Is it intentional that assertj-db 1.1.0 requires java 8? 

When I try to use it with java 7 I get:

>java.lang.UnsupportedClassVersionError: org/assertj/db/type/Table : Unsupported major.minor version 52.0

**Comment by regis1512** [comment]
I have updated the version of assertj-parent-pom.
It is certainly that which is wrong

**Comment by regis1512** [comment]
So i release a version 1.1.1 to fix that

**Comment by PascalSchumacher** [comment]
Thanks!

**Comment by joel-costigliola** [comment]
What you should probably do is to set the compiler plugin to 1.7 as in assertj-core 2.x:
```xml
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>1.7</source>
          <target>1.7</target>
          <encoding>${project.build.sourceEncoding}</encoding>
        </configuration>
      </plugin>
```
Doing that will let you use the latest parent pom (no need to release 1.1.2 for that).
