### ISSUE TITLE
add code examples in javadoc

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-db#4]
It's hard to understand what some assertion does without example.

for ex: `AssertionsOnDataType.isOnDataType`.

**Comment by regis1512** [comment]
For the moment, i added example for this one (datatype_isontable_assertion_examples and datatype_isonrequest_assertion_examples methods in ChangesAssertionExamples).
I will check the other assertion methods and confirm here when if will be done.

Thanks.

**Comment by regis1512** [comment]
I think i have added a example for each kind of assertion in https://github.com/regis1512/assertj-examples/tree/master/assertions-examples/src/test/java/org/assertj/examples/db.

Please let me know when i can create a pull request
