### ISSUE TITLE
Add BDDAssertions?

### ISSUE THREAD

**Issue by PascalSchumacher** [joel-costigliola/assertj-db#41]
I prefer to use `then` over `assertThat` for assertions, so I always use http://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/BDDAssertions.html of assertj-core.

Maybe this could also be added to assertj-db?

**Comment by regis1512** [comment]
It is possible to add another entry point.
But why the name of the class is BDDAssertions in assertj-core ?

**Comment by joel-costigliola** [comment]
[Behaviour Driven Development](https://en.wikipedia.org/wiki/Behavior-driven_development) `then` part ;-)

**Comment by regis1512** [comment]
Thanks. Understood.
