### ISSUE TITLE
Add support for char column type in TableRowValueAssert#isEqualTo

### ISSUE THREAD

**Issue by men-devnat-grenoble** [joel-costigliola/assertj-db#43]
As a tester I want to be able to check character value on char type column.
At the moment char I have to use the isEqualTo(String) signature to perform this test

`assertThat(table).row(3).value("code").isEqualTo('A')`

Thanks for your job!

**Comment by regis1512** [comment]
Thanks for your suggestion.
It will be a good thing.
I will try to add it in the next version.
