### ISSUE TITLE
Field containing '%' causes formatflagsconversionmismatchexception in db dump

### ISSUE THREAD

**Issue by CobaltChicken** [joel-costigliola/assertj-db#52]
java.util.FormatFlagsConversionMismatchException at TestLoadFilesIT.java:199

Seems to happen when you attempt to dump a database record containing a percentage sign in a column. The text is fed through String.format and percentage characters are treated as a placeholder field.

Literal % signs need to be escaped before calling format().

**Comment by joel-costigliola** [comment]
Thanks for the feedback !
Could you write a small unit test showing the problem ?

**Comment by regis1512** [comment]
During tests, i identify a problem with a column name with %.
It was a format exception with String.format(...).
I close this issue and hope it was the same problem.
