### ISSUE TITLE
getConnection() leak?

### ISSUE THREAD

**Issue by juntaki** [joel-costigliola/assertj-db#54]
Is this connection closed?
I got the error `org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections`, with many use of `setStartPointNow()` and `setEndPointNow()`.
https://github.com/joel-costigliola/assertj-db/blob/542eedb950f9eedf56bda6648568d565b1416cd6/src/main/java/org/assertj/db/type/Changes.java#L274

**Comment by PascalSchumacher** [comment]
Yes it is closed, because the try-with-resources statement closes the connection after executing the code block.

**Comment by juntaki** [comment]
Thanks!
