### ISSUE TITLE
Rename isOfAnyOfTypes to ...

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-db#6]
I find `isOfAnyOfTypes`not to sound well, so I suggest to rename it to:
1. `isOfAnyType` or 
2. `hasTypeIn` 

I'm not sure what works best...

**Comment by regis1512** [comment]
What do you think about mixing your two suggestions ?
-> `isOfAnyTypeIn`

Thks

**Comment by joel-costigliola** [comment]
good one ! :)

**Comment by regis1512** [comment]
That's done.
Thanks ;)

**Comment by PascalSchumacher** [comment]
This can be closed I guess?

**Comment by regis1512** [comment]
Yes we can ;)
