### ISSUE TITLE
Make a way to view the data of a Table, of a Request or of Changes

### ISSUE THREAD

**Issue by regis1512** [joel-costigliola/assertj-db#9]
It could be interesting for the user to have the possibility to print like with toString or view like like a HTML document the information in a Table, a Request or Changes for example.

That could make easier the debugging of a test.

**Comment by regis1512** [comment]
It is an idea for a next release.
For the moment, the goal is to make the first.

**Comment by regis1512** [comment]
I started to work on that.
Like start of the assertions is Assertions class, the display of the data will be Displaying class (in a own package).
I think to make it working like assertions for the navigation.
It will something like : 
```
Displaying.display(table).row().onConsole();
Displaying.display(requet).column("name").withType(TypeDisplay.HTML).inFile("test.html");
```

**Comment by otoniel-isidoro-sofist** [comment]
good idea :+1:
